CI(GitHub Actions): `--no-git-checks`
Summary:
```
ERR_PNPM_GIT_UNKNOWN_BRANCH  The Git HEAD may not attached to any branch, but your "publish-branch" is set to "master|main".
If you want to disable Git checks on publish, set the "git-checks" setting to "false", or run again with "--no-git-checks".
Error: Process completed with exit code 1.
```

Signed-off-by: Yongmin Hong <revi@omglol.email>

Test Plan: Land and push tag again.

Reviewers: O1 revi & automations, revi

Reviewed By: O1 revi & automations, revi

Differential Revision: https://issuetracker.revi.xyz/D636