Revert "RobotsTxt: specify more verbose classes"
Summary:
This reverts commit 88946a7fe2e1a5447fca8adbee28f554993be5fe.

PHP Fatal error:  Cannot override final method PhabricatorRobotsController::processRequest() in /var/www/phorge/phorge/src/extensions/PhabricatorCustomRobotsTxtController.php on line 13

Fatal error: Cannot override final method PhabricatorRobotsController::processRequest() in /var/www/phorge/phorge/src/extensions/PhabricatorCustomRobotsTxtController.php on line 13

Signed-off-by: Yongmin Hong <revi@omglol.email>

Reviewers: #acl_sudoers, #blessed_reviewers, revi

Reviewed By: #acl_sudoers, #blessed_reviewers, revi

Differential Revision: https://issuetracker.revi.xyz/D10